{
 "title": "Artemis",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests/second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "\"artemis-db\"",
     "measure": "value_count",
     "rawQuery": "SELECT time, (sum(measure_value::double) / 10) AS requests_per_second\nFROM \"artemis-db\".\"http_reqs\"\nWHERE time BETWEEN ago(1d) AND now() \nAND measure_name = 'value_sum'\nGROUP BY time\nORDER BY time ASC",
     "table": "\"data_received\""
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "database": "\"artemis-db\"",
     "measure": "value_sum",
     "rawQuery": "SELECT time, avg(measure_value::double) AS http_request_duration\nFROM \"artemis-db\".\"http_req_duration\"\nWHERE time BETWEEN ago(1d) AND now() \nAND measure_name = 'value_mean'\nGROUP BY time\nORDER BY time ASC",
     "table": "\"http_req_failed\""
    }
   ]
  },
  {
   "title": "HTTP Request Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "database": "\"artemis-db\"",
     "measure": "value_sum",
     "rawQuery": "SELECT time, sum(measure_value::double) AS requests_failed\nFROM \"artemis-db\".\"http_req_failed\"\nWHERE time BETWEEN ago(1d) AND now() \nAND measure_name = 'value_count'\nAND status = '0'\nGROUP BY time\nORDER BY time ASC",
     "table": "\"http_reqs\""
    }
   ]
  },
  {
   "title": "VUs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "database": "\"artemis-db\"",
     "measure": "value_sum",
     "rawQuery": "SELECT time, (avg(measure_value::double) * 10) as vus\nFROM \"artemis-db\".\"vus\"\nWHERE time BETWEEN ago(1d) AND now() \nAND measure_name = 'value_mean'\nGROUP BY time\nORDER BY time ASC",
     "table": "\"http_reqs\""
    }
   ]
  }
 ]
}